---
  extends: airbnb/base
  parser: babel-eslint
  env:
    es6: true
    browser: true
    node: true
    mocha: true
  settings:
    import/resolver: webpack
  globals:
    google: false
    twttr: true
    Auth0: false
    $: false
  rules:
    class-methods-use-this: off
    consistent-return: off
    comma-dangle:
      - error
      - always-multiline
    no-trailing-spaces:
      - error
      - skipBlankLines: true
    no-confusing-arrow:
      - error
      - allowParens: true
    block-spacing:
      - error
      - never
    arrow-spacing:
      - error
      - before: true
        after: true
    object-curly-spacing:
      - 2
      - always
    space-in-parens:
      - error
      - never
    space-before-function-paren:
      - error
      - never
    space-before-blocks:
      - error
      - always
    keyword-spacing:
      - error
      - before: true
        after: true
    quotes:
      - error
      - single
      - avoidEscape: true
        allowTemplateLiterals: true
    global-require: off
    import/no-unresolved: off
    import/no-duplicates: off
    import/no-named-as-default: off
    import/no-absolute-path: off
    import/no-named-as-default-member: off
    import/no-extraneous-dependencies: off
    import/prefer-default-export: off
    import/export: off
    import/extensions: off
    no-irregular-whitespace: off
    no-unused-expressions:
      - error
      - allowShortCircuit: true
        allowTernary: true
    no-underscore-dangle:
      - error
      - allowAfterThis: true
        allow:
          - _handleNestedListToggle
          - _disableDisplay
          - _DEPRECATION_NOTICE
          - __IS_SMOOTH_SCROLLING
          - __scroll__direction
          - __CA_DELAYED_MODAL
          - _wq
          - __dataID__
          - _fbq
          - _hsq
    no-param-reassign:
      - error
      - props: false
